scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.floorDark4, function (sprite, location) {
    mySprite.setImage(img`
        ........................
        .....ffff...............
        ...fff11fff.............
        ..fff1211fff............
        .fffdddd2dfff...........
        .ffd121112ddf...........
        .f21ffffff1df...........
        .ffffd22dffff...........
        ffdf121121f2ff..........
        f2d212dd211d2f..........
        .ffffddddd2df...........
        fd2ddf121ddf............
        fd2d2fd2d2f12...........
        fd2d2fd2dd2d1...........
        .fd2f1d211f21...........
        ..ffffffff..............
        ....ff..ff..............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleBlueCrystal, function (sprite, location) {
    mySprite.setImage(img`
        ........................
        .....ffff...............
        ...fff66fff.............
        ..fff6666fff............
        .fff888888fff...........
        .ff866666688f...........
        .f86ffffff68f...........
        .ffffeeeeffff...........
        ffefbf44fbfeff..........
        fee41fddf14eef..........
        .ffffdddddeef...........
        fddddf444eef............
        fbbbbf6668f4e...........
        fbbbbf6668fd4...........
        .fccf86668f44...........
        ..ffffffff..............
        ....ff..ff..............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
    music.baDing.play()
    game.over(true)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.darkGroundCenter, function (sprite, location) {
    tiles.setWallAt(tiles.getTileLocation(4, 10), true)
    mySprite.setImage(img`
        ........................
        .....ffff...............
        ...fff66fff.............
        ..fff6666fff............
        .fff888888fff...........
        .ff866666688f...........
        .f86ffffff68f...........
        .ffffeeeeffff...........
        ffefbf44fbfeff..........
        fee41fddf14eef..........
        .ffffdddddeef...........
        fddddf444eef............
        fbbbbf6668f4e...........
        fbbbbf6668fd4...........
        .fccf86668f44...........
        ..ffffffff..............
        ....ff..ff..............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestClosed, function (sprite, location) {
    tiles.setWallAt(tiles.getTileLocation(5, 10), false)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.darkGroundEast, function (sprite, location) {
    mySprite.setImage(img`
        ........................
        .....ffff...............
        ...fff66fff.............
        ..fff6666fff............
        .fff888888fff...........
        .ff866666688f...........
        .f86ffffff68f...........
        .ffffeeeeffff...........
        ffefbf44fbfeff..........
        fee41fddf14eef..........
        .ffffdddddeef...........
        fddddf444eef............
        fbbbbf6668f4e...........
        fbbbbf6668fd4...........
        .fccf86668f44...........
        ..ffffffff..............
        ....ff..ff..............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `)
    tiles.setWallAt(tiles.getTileLocation(4, 13), true)
    tiles.setWallAt(tiles.getTileLocation(4, 12), true)
    tiles.setWallAt(tiles.getTileLocation(4, 11), true)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleRedCrystal, function (sprite, location) {
    music.powerDown.play()
    game.over(false)
})
let mySprite: Sprite = null
tiles.setTilemap(tilemap`level1`)
mySprite = sprites.create(img`
    ........................
    .....ffff...............
    ...fff66fff.............
    ..fff6666fff............
    .fff888888fff...........
    .ff866666688f...........
    .f86ffffff68f...........
    .ffffeeeeffff...........
    ffefbf44fbfeff..........
    fee41fddf14eef..........
    .ffffdddddeef...........
    fddddf444eef............
    fbbbbf6668f4e...........
    fbbbbf6668fd4...........
    .fccf86668f44...........
    ..ffffffff..............
    ....ff..ff..............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
tiles.placeOnRandomTile(mySprite, sprites.dungeon.collectibleInsignia)
forever(function () {
    controller.moveSprite(mySprite)
    scene.cameraFollowSprite(mySprite)
})
